name 'example42-etcprofile'
version '2.0.4'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-etcprofile'
summary 'A Puppet module for to manage /etc/profile and /etc/profile.d'
description 'This is a Puppet module for to manage /etc/profile and /etc/profile.d'
dependency 'example42/puppi', '>=2.0.0'
